### PR TITLE
kill instead of stop at exit

### PR DESCRIPTION
**Pull request by fonsp**
In case the process is stuck in a `while true end`?

### CODE REVIEW

**Comment by fonsp** [comment]
@savq What would be best here?

**Comment by fonsp** [comment]
Can the atexit hook be blocking? Then we could try to `stop` the processes cleanly, wait until they all finished with a timeout, and then `kill` remaining processes and release the block.

**Comment by fonsp** [comment]
@habemus-papadum WDYT?

**Comment by habemus-papadum** [comment]
@fonsp  This is always tricky.   I will look at the source for kill.

**Comment by fonsp** [comment]
What we probably want to do is copy distributed:

We need a `kill(::Malt.Worker)` function that looks like:

```julia

function kill(manager::LocalManager, pid::Int, config::WorkerConfig; exit_timeout = 15, term_timeout = 15)
    # First, try sending `exit()` to the remote over the usual control channels
    remote_do(exit, pid)

    timer_task = @async begin
        sleep(exit_timeout)

        # Check to see if our child exited, and if not, send an actual kill signal
        if !process_exited(config.process)
            @warn("Failed to gracefully kill worker $(pid), sending SIGTERM")
            kill(config.process, Base.SIGTERM)

            sleep(term_timeout)
            if !process_exited(config.process)
                @warn("Worker $(pid) ignored SIGTERM, sending SIGKILL")
                kill(config.process, Base.SIGKILL)
            end
        end
    end
    errormonitor(timer_task)
    return nothing
end
# (taken from distributed source code)
```

Then the atexit hook also calls this function. :)

**Comment by fonsp** [comment]
PS the `atexit` can be blocking:

```
➜  ~ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.3 (2022-11-14)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> atexit(() -> begin sleep(5); @info "asdf" end)

julia> 
[ Info: asdf
➜  ~ 
```

And to avoid killing it twice at exit (once with the finalizer and once with atexit) we need to come up with something.

Maybe check if it's running and do a lock?

Add this field to the worker `is_already_being_finalized::Ref{Bool}` wowwwww and make it atomic. That requires Julia 1.7

**Comment by habemus-papadum** [comment]
killing an already ended process is not a problem (according to the docs)
```
kill(p::Process, signum=Base.SIGTERM)

  Send a signal to a process. The default is to terminate the process. Returns successfully if the process has already exited, but throws an error if killing the process failed for
  other reasons (e.g. insufficient permissions).
```

**Comment by Pangoraw** [comment]
> killing an already ended process is not a problem (according to the docs)

awesome, thanks!

**Comment by fonsp** [comment]
PR ready now, would be nice to have a test

**Pull request closed without merging**
